// Generated by gencpp from file becker/imumsg.msg
// DO NOT EDIT!


#ifndef BECKER_MESSAGE_IMUMSG_H
#define BECKER_MESSAGE_IMUMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace becker
{
template <class ContainerAllocator>
struct imumsg_
{
  typedef imumsg_<ContainerAllocator> Type;

  imumsg_()
    : imumsg(0)  {
    }
  imumsg_(const ContainerAllocator& _alloc)
    : imumsg(0)  {
  (void)_alloc;
    }



   typedef int64_t _imumsg_type;
  _imumsg_type imumsg;




  typedef boost::shared_ptr< ::becker::imumsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::becker::imumsg_<ContainerAllocator> const> ConstPtr;

}; // struct imumsg_

typedef ::becker::imumsg_<std::allocator<void> > imumsg;

typedef boost::shared_ptr< ::becker::imumsg > imumsgPtr;
typedef boost::shared_ptr< ::becker::imumsg const> imumsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::becker::imumsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::becker::imumsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace becker

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'becker': ['/home/pi/catkin_ws/src/becker/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::becker::imumsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::becker::imumsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::becker::imumsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::becker::imumsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::becker::imumsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::becker::imumsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::becker::imumsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9db9cbcb4534dd931b602a8e2177c412";
  }

  static const char* value(const ::becker::imumsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9db9cbcb4534dd93ULL;
  static const uint64_t static_value2 = 0x1b602a8e2177c412ULL;
};

template<class ContainerAllocator>
struct DataType< ::becker::imumsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "becker/imumsg";
  }

  static const char* value(const ::becker::imumsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::becker::imumsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 imumsg\n\
";
  }

  static const char* value(const ::becker::imumsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::becker::imumsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.imumsg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct imumsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::becker::imumsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::becker::imumsg_<ContainerAllocator>& v)
  {
    s << indent << "imumsg: ";
    Printer<int64_t>::stream(s, indent + "  ", v.imumsg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BECKER_MESSAGE_IMUMSG_H
